CREATE DATABASE IF NOT EXISTS ImageDatabase;
Use ImageDatabase;
CREATE TABLE IF NOT EXISTS Images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image BLOB,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    pose CHAR(50)
);
